# Generated by Django 3.1.2 on 2020-10-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
