# Generated by Django 3.1.2 on 2020-11-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0002_auto_20201031_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasto',
            name='cantidad',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='ingreso',
            name='cantidad',
            field=models.FloatField(default=0.0),
        ),
    ]
