# Generated by Django 3.1.2 on 2020-11-10 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0003_padre_dni'),
        ('Contabilidad', '0005_recibo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='recibo',
            name='Padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.padre'),
        ),
    ]
