# Generated by Django 3.1.2 on 2020-11-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0006_auto_20201110_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='Padre',
            new_name='padre',
        ),
    ]
