# Generated by Django 3.1.2 on 2020-11-10 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contabilidad', '0008_remove_recibo_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='padre',
        ),
        migrations.AddField(
            model_name='recibo',
            name='apellidos',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='recibo',
            name='nombre',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
