# Generated by Django 3.1.2 on 2020-11-21 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0005_auto_20201114_1120'),
        ('Contabilidad', '0010_recibo_dni'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibo',
            name='apellidos',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='recibo',
            name='nombre',
        ),
        migrations.AddField(
            model_name='recibo',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.padre'),
        ),
    ]
