# Generated by Django 3.1.2 on 2020-10-20 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Alumnos', '0002_auto_20201006_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Concepto', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=12)),
                ('año', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
            },
        ),
        migrations.CreateModel(
            name='Adeudo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Importe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Concepto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adeudos.concepto')),
                ('Mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Adeudos.mes')),
                ('Padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.padre')),
            ],
            options={
                'verbose_name': 'Adeudo',
                'verbose_name_plural': 'Adeudos',
            },
        ),
    ]
