# Generated by Django 3.1.2 on 2020-10-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adeudos', '0002_auto_20201021_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeudo',
            name='Importe',
            field=models.IntegerField(default=0.0),
        ),
    ]
