# Generated by Django 3.1.2 on 2020-10-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adeudos', '0003_auto_20201031_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adeudo',
            name='Importe',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
