# Generated by Django 3.1.2 on 2020-11-21 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0005_auto_20201114_1120'),
        ('Adeudos', '0005_auto_20201114_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='adeudo',
            name='Alumno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumnos.alumno'),
        ),
    ]
