# Generated by Django 3.1.2 on 2020-11-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Adeudos', '0006_adeudo_alumno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adeudo',
            name='Padre',
        ),
    ]
