# Generated by Django 3.1 on 2020-10-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padre',
            name='Telefono1',
            field=models.CharField(max_length=12, verbose_name='Tlf 1'),
        ),
        migrations.AlterField(
            model_name='padre',
            name='Telefono2',
            field=models.CharField(max_length=12, verbose_name='Tlf 2'),
        ),
    ]
