# Generated by Django 3.1.2 on 2020-11-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0003_padre_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padre',
            name='NumeroCuenta',
            field=models.CharField(max_length=24, verbose_name='Numero de Cuenta'),
        ),
    ]
