# Generated by Django 3.1.2 on 2020-11-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0004_auto_20201114_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padre',
            name='Telefono1',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Tlf 1'),
        ),
        migrations.AlterField(
            model_name='padre',
            name='Telefono2',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Tlf 2'),
        ),
    ]
